spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/holidaymailer
    username: mailer
    password: secret123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
    host: localhost
    port: 1025
    username: fplive@foxmail.com
    password: kpcbkdaodvdcdggh
    protocol: smtp
  application:
    name: holiday-mailer

coze:
  api:
    baseUrl: "https://api.coze.cn/"
    token: "pat_O0kRoO54XpYDXJsibUFHeCH1ckvkErCMXjJszWq1v5TQgAkc1HifxllfQsCxSqW4"
    workflowId: "7524227986921783342"


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ai-mail-service


